spring:
  zipkin: #new
    base-url: http://localhost:9411/ #new
    enabled: true #new
  application:
    name: configuration-service
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Parisj7/ExamenMicroservicios
          default-label: main
server:
  port: 8888